version: '3'

services:
  mysql:
    container_name: mysql
    image: mysql
    environment:
      MYSQL_DATABASE: "SPRING_BATCH"
      MYSQL_ROOT_PASSWORD: "1234"
      TZ: "Asia/Seoul"
    ports:
      - "3306:3306"
    command:
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_unicode_ci"